name: SL2Reps
version: "1.0"
license: "GPL-2.0-or-later"
date: 2021-12-28
description: |
    Constructing symmetric representations of SL(2,Z).

authors:
    - name: Siu-Hung Ng
      url: https://www.math.lsu.edu/~rng/
    - name: Yilong Wang
      url: https://yilongwang11.github.io
    - name: Samuel Wilson
      url: https://snw-0.github.io

maintainers:
    - name: Samuel Wilson
      url: https://snw-0.github.io

GAP: ">= 4.11"

www: https://snw-0.github.io/sl2-reps
readme: sl2-repsREADME.md
packageinfo: https://snw-0.github.io/sl2-repsPackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/snw-0/sl2-reps/releases/download/v1.0/SL2Reps-1.0.tar.gz

abstract: |
    The <span class="pkgname">SL2Reps</span> package provides provides methods for constructing and testing matrix   presentations of the representations of SL(2,Z) whose kernels are congruence subgroups   of SL(2,Z).

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    representations.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NWW21</span>]   <b class='BibAuthor'>Ng, S.-H., Wang, Y. and Wilson, S.</b>,
     <i class='BibTitle'>SL2Reps, Constructing symmetric representations of SL(2,Z).,
             Version 1.0</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://snw-0.github.io/sl2-reps">https://snw-0.github.io/sl2-reps</a></span>.
    </p>
    

bibtex: |
    @misc{ SL2Reps1.0,
      author =           {Ng, S.-H. and Wang, Y. and Wilson, S.},
      title =            {{SL2Reps}, Constructing symmetric representations of SL(2,Z)., {V}ersion 1.0},
      month =            {Dec},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href    {https://snw-0.github.io/sl2-reps}   {\texttt{https://snw-0.github.io/}\discretionary
                          {}{}{}\texttt{sl2-reps}}},
      keywords =         {representations},
      printedkey =       {NWW21}
    }

